--- 
title: "Aproximações para a duração média de passeios aleatórios"
bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl
lang: pt-BR

authors:
  - name: "Eduardo Yukio Garrafa Ishihara"
  - name: "Gustavo Silva Garone"
  - name: "Elisabeti Kira"

abstract: > 
            Inspirados na física, propusemos aproximações para a duração de
            passeios aleatórios diversos, em especial, os de difícil derivação
            analítica. Para avaliar as aproximações, utilizamos simulações de Monte Carlo
            na linguagem Julia. Analisamos o desempenho desta linguagem comparando-a com
            a linguagem Python. Com modelos (passeios) mais sofisticados, utilizamos
            recursos computacionais para solução de sistemas lineares na construção de
            novas aproximações, descrevendo o uso de paralelismo e de outras
            ferramentas. Exibimos e analisamos os resultados obtidos, assim como os
            algoritmos utilizados.

keywords:
    - Passeio Aleatório
    - Monte Carlo
    - Estimação
date: last-modified
date-format: long
format:
  pdf:
    documentclass: article
    fontsize: 12pt
    monofont: "Consolas"
    geometry:
      - top=20mm
      - left=20mm
      - bottom=20mm
      - right=20mm
    number-sections: true
    include-in-header:
      text: |
        \usepackage{authblk}
  html:
    theme: cosmo
engine: julia
julia:
  env: ["QT_STYLE_OVERRIDE=windows"]
execute:
  echo: false
  keep-ipynb: true
  # eval: false
  cache: true
fig-cap-location: bottom 
---

```{julia}
#| output: false
# Pacotes utilizados no artigo e suas versões
using Pkg
Pkg.add(["Plots", "Distributions", "Statistics", "Random", "LaTeXStrings"])
versioninfo()
Pkg.status()
```

# Introdução

Neste artigo, estudaremos a duração de passeios aleatórios e suas aproximações.
Temos como objetivo descrever modelos de passeios como a "Ruína do Jogador" de
Pascal, discutido em @edwards_pascals_1983, generalizando-o para múltiplas
dimensões. Abordaremos técnicas analíticas, computacionais e de estimativas para
a duração esperada destes passeios. 

Começaremos por definir o modelo que será utilizado para descrever os passeios
aleatórios, acompanhado de exemplo. Em seguida, descreveremos resultados
anteriores do cálculo de probabilidades envolvendo esses passeios. Então,
apresentaremos um estimador para a duração desses e partiremos para sua
avaliação. Compará-lo-emos com os resultados probabilísticos obtidos. Quando
avançarmos para passeios em que resultados analíticos não são factíveis,
iniciaremos a comparação do estimador com simulações de Monte Carlo.

Descrevemos e justificamos pela literatura a adoção da linguagem de programação
*Julia*, essencial para possibilitar a execução eficiente de simulações
computacionalmente intensivas em passeios mais complexos.

Em dimensões maiores, forneceremos, até onde é computacionalmente possível,
resultados exatos para a duração esperada de passeios aleatórios. Para obter
esses resultados, utilizaremos métodos para solução de sistemas lineares
extensos e empregaremos técnicas de computação paralela, que serão brevemente
discutidas.

Este artigo cobrirá tanto o desenvolvimento teórico matemático do estimador e
modelos, quanto a descrição do aspecto computacional desta pesquisa, incluindo
os algoritmos utilizados. Os códigos completos estão disponíveis para consulta e
*Download* na versão digital desta publicação.

# A Ruína do Jogador e outros passeios aleatórios

Postulado por Blaise Pascal para Fermat no século XVII @edwards_pascal_1983, o
problema que originaria a Ruína do Jogador consistia em determinar a
probabilidade de vitória de um jogador em um jogo de apostas, como o lançamento
de dados ou moedas, contra um adversário. A característica principal deste jogo
é que os jogadores transferem seus pontos, ou fortunas, entre si. Portanto, o
jogo termina quando um dos jogadores perde toda a sua fortuna, ou seja, vai à
ruína.

Podemos descrever a fortuna do jogador nesses jogos como um passeio aleatório
unidimensional em $\mathbb{Z}$, usualmente considerando apenas o espaço de
estados $\mathbb{N}$, com as probabilidades envolvidas nas jogadas controlando o
comportamento do passeio. Por exemplo, na aposta sobre o resultado do lançamento
de uma moeda honesta, temos um passeio simétrico:

$$
\begin{aligned}
\mathbb{P}(X = +1) &= 0.5, \\
\mathbb{P}(X = -1) &= 0.5.
\end{aligned}
$$

A "Ruína do Jogador" é o nome do resultado que, num jogo contra uma "casa de
apostas" com fortuna infinita ou muito maior que a sua, o jogador
inevitavelmente irá à ruína quando o jogo for justo (quando o passeio configurar
um martingal) em tempo finito.

Podemos estender esse passeio para jogos mais complexos, desde alterações
simples, como probabilidades desiguais, até jogos com mais jogadores, fortunas
distintas (múltiplas dimensões) e regras variáveis ao longo do tempo (jogada) ou
espaço (fortuna). Assim, conseguimos modelar uma grande variedade de passeios
aleatórios com base no princípio da troca de fortuna.

# Modelando passeios aleatórios

## Modelo 

:::{#def-modelodiscreto}

Considere que o jogador $A$ começa com uma fortuna inicial com um total $\$N$ em
jogo, $\$a$, $0 \leq a \leq N$, fornecendo um espaço de estados 
$\{0, 1, \dots, a, \dots, N\}$. 
Cada rodada produz um resultado aleatório independente $X_i$, $i=1,2,\dots$,
representando o ganho ou perda naquela etapa. Isso será chamado de variável
"regra". Após $n$ rodadas, a fortuna do jogador $A$ é dada por

$$
S_n = a + \sum_{i=1}^n X_i.
$$

A **duração do jogo** é o primeiro tempo $n$ tal que $S_n \leq 0$ (ruína) ou
$S_n \geq N$ (vitória). É denotada por $\tau_{X, a, N}$, a regra de parada.

Podemos também relacionar $X$ com a posição atual do passeio, $X_{n} := X_{S_n}$
estendendo esse modelo para passeios em meio não homogêneo: definimos $\pmb{R} =
\{X_1, \dots, X_N\}$ e $\tau_{\pmb{R}, a, N}$.
:::

::: {#rem-tempo}
Neste artigo, não trataremos de passeios em meio não homogêneo no tempo, mas
podemos, se preciso, estender esse modelo para incluir essa característica.
:::

Para ajudar no entendimento deste modelo, oferecemos um
exemplo:

:::{#exm-modelodiscreto}

Considere um jogador apostando em um casino no lançamento de uma moeda
honesta. Se a moeda cair em cara, o jogador ganha um dólar; se cair em
coroa, perde um dólar. O jogo termina quando o jogador atingir cem dólares ou
vá à ruína (seu saldo chegue em zero). O jogador começa com cinquenta
dólares.

Podemos modelar esse jogo no modelo da @def-modelodiscreto:

Seja $a = 50$ e $N = 100$. A variável regra do jogo é dada por

$$
X = \begin{cases}
-1, & \mathbb{P}(X = -1) = 0.4, \\
+1, & \mathbb{P}(X = +1) = 0.6.
\end{cases}
$$

Nota-se que a regra é a mesma para todo estado $S_n$ enquanto o
jogo durar, ou seja, o passeio está homogêneo no espaço e tempo.

Após $5$ jogadas, o jogo tomou o seguinte percurso:
$$
\pmb{x} = \{x_1, x_2, x_3, x_4, x_5\} = \{1, -1, 1, 1, -1\}.
$$

temos então que a posição (fortuna) atual do jogador é
$$
S_5 = 50 + (1 - 1 + 1 + 1 -1) = 51.
$$
:::

## Jogos unitários e não unitários

Definimos um jogo como **unitário** se a variável regra $X$ assume apenas
valores inteiros unitários, ou seja, $X: \Omega \rightarrow \{-1, +1\}$. Caso
contrário, o jogo é dito **não unitário**. No @exm-modelodiscreto, o
jogo é unitário.

Essa distinção faz-se importante, uma vez que, como apresentaremos na próxima
seção, a abordagem analítica para determinar a duração esperada do jogo difere
entre jogos unitários e não unitários. De fato, em jogos não unitários, a
determinação analítica de $\mathbb{E}[\tau_{X, a, N}]$ pode ser muito mais
complexa, ou até mesmo inviável.

## Abordagem analítica para determinar $\mathbb{E}[\tau_{X, a, N}]$ {#sec-anali}

Retomamos a variável aleatória de regra $X_i, i \in \mathbb{Z}^+$,
para descrever a quantia ganha pelo jogador $A$ na $i$-ésima rodada,
Podemos considerar $X_i, i \in \mathbb{Z}^+$,
independentes e com mesma distribuição de $X$ dada por

$$
X = \begin{cases}
    +1, & \mathbb{P}(X=+1)=p \\
    -1, & \mathbb{P}(X=-1)=q
\end{cases}
$$

Adicionalmente, definimos $\tau_{X,a,N}$,
como o número de rodadas até o fim do jogo
em que o resultado de cada rodada é representado pela variável aleatória $X$,
o jogador $A$ começa com $a$ reais e o jogo termina quando $A$ chega a $0$ ou $N$ reais.
Definimos $\mu_{a} = \mathbb{E}[\tau_{X,a,N}]$,
ou seja, é o número esperado de rodadas que durará o jogo
em que que o resultado de cada rodada é representado pela variável aleatória $X$,
o jogador $A$ começa com $a$ reais e o jogo termina quando $A$ chega a $0$ ou $N$ reais.

$$
\begin{aligned}
\mathbb{E}[\tau_{X, a, N}]
&= \mathbb{E}[\tau_{X, a, N}|X_1=1] \mathbb{P}(X_1=1)+\mathbb{E}[\tau_{X, a, N}|X_1=-1] \mathbb{P}(X_1=-1) \\
&= \mathbb{E}[\tau_{X, a, N}|X_1=1] \: p + \mathbb{E}[\tau_{X, a, N}|X_1=-1] \: q \\
&= (\mathbb{E}[\tau_{X, a+1,N}]+1) \: p + (\mathbb{E}[\tau_{X, a-1,N}]+1) \: q \\
&= p \: \mathbb{E}[\tau_{X, a+1,N}] + q \: \mathbb{E}[\tau_{X, a-1,N}] + 1 \\
\mu_{a} &= p \mu_{a+1} + q \mu_{a-1} + 1  
\end{aligned}
$$
Trata-se, portanto, de uma equação de diferenças finitas não homogênea,
cuja solução é a esperança desejada.

Tomemos $\mu_{a} = \lambda ^a$ e, temporariamente, desconsideraremos a constante $1$
na equação de diferenças finitas.
$$
\begin{aligned}
& \phantom{\Rightarrow;;}\lambda ^a = p \:  \lambda ^{a+1} + q \: \lambda ^{a-1} \\
& \Rightarrow p \:  \lambda ^ 2 -\lambda + q = 0 \\
& \Rightarrow \lambda_1 = \frac{q}{p}; \:  \lambda_2 = 1
\end{aligned}
$$

Para $\frac{p}{q} = 1$:
$$
\lambda_1 = \lambda_2 = 1
$$
Temos a seguinte equação característica:
$$
\mu_{a} = \alpha + \beta a + \gamma a^2
$$

Tomemos $\mu_{a} = \gamma a^2$. Juntando as equações:
$$
\begin{aligned}
& \phantom{\Rightarrow;;}
\gamma a^2 = \frac{1}{2} \gamma (a-1)^2 + \frac{1}{2} \gamma (a+1)^2 + 1 \\
& \Rightarrow 2 \gamma a^2 = \gamma a^2 - 2 \gamma a + \gamma + \gamma a^2 + 2\gamma a + \gamma + 2\\
& \Rightarrow \gamma = -1
\end{aligned}
$$

Aplicando as seguintes condições de fronteira:
$$
\begin{aligned}
& \phantom{\Rightarrow \,\,}\begin{cases} \mu_{0} = 0 \\ \mu_{N} = 0 \end{cases} \\
&\Rightarrow
\begin{cases} \mu_{0} = 0 = \alpha + \beta 0 + \gamma 0^2 \\ 
              \mu_{N} = 0 = \alpha + \beta N + \gamma N^2   \end{cases}\\
& \Rightarrow 
\begin{cases} \alpha = 0 \\ 
              \beta  = N  \end{cases} \\
\mu_{a} &=  Na-a^2 = a(N-a)
\end{aligned}
$$
Nota-se que, neste modelo, a esperança da duração do jogo é máxima
quando os dois jogadores começam com a mesma fortuna.

Para jogos não simétricos, isto é, jogos em que $\mathbb{E}[X] \neq 0$, temos a
seguinte equação característica:
$$
\mu_{a} = \alpha \lambda_1^a + \beta \lambda_2^a + \gamma a
$$

Tomemos $\mu_{a} = \gamma a$:

$$
\begin{aligned}
& \phantom{\Rightarrow;;}\gamma a = p \:  \gamma ({a+1}) + q \: \gamma ({a-1}) +1 \\
& \Rightarrow \gamma = \frac{1}{q-p}
\end{aligned}
$$

Substituindo e usando as fronteiras:
$$
\begin{aligned}
& \phantom{\Rightarrow;;} \mu_{a} = \alpha \left( \frac{q}{p} \right) ^a + \beta + \frac{a}{q-p} \\
& \Rightarrow \begin{cases} \mu_{0} = 0 \\ \mu_{N} = 0 \end{cases}\\
& \Rightarrow
\begin{cases} \mu_{0} = 0 = \alpha \left( \frac{q}{p} \right) ^0 + \beta + \frac{0}{q-p} \\ 
              \mu_{N} = 0 = \alpha \left( \frac{q}{p} \right) ^N + \beta + \frac{N}{q-p}   \end{cases}\\
& \Rightarrow 
\begin{cases} \alpha = \frac{N}{p-q}\frac{1}{\left( \frac{q}{p} \right)^N-1} \\ 
              \beta  = -\frac{N}{p-q}\frac{1}{\left( \frac{q}{p} \right)^N-1} \end{cases} \\ \\ \\
\mu_{a} &= \frac{N}{p-q}\frac{1}{\left( \frac{q}{p} \right)^N-1} \left( \frac{q}{p} \right)^a - \frac{N}{p-q}\frac{1}{\left( \frac{q}{p} \right)^N-1} + \frac{a}{q-p} \\
\mu_{a} & = \frac{a}{q-p}-\frac{N}{q-p} \left( \frac{1- \left( \frac{q}{p} \right)^a}
        {1- \left( \frac{q}{p} \right)^N}\right)
\end{aligned}
$$

Finalmente,
$$
\mathbb{E}[\tau_{x, a, N}] = 
\begin{cases}
a(N-a), & \mathbb{E}[X] = 0 \\
\frac{a}{q-p}-\frac{N}{q-p} \left( \frac{1- \left( \frac{q}{p} \right)^a} {1- \left( \frac{q}{p} \right)^N}\right), &
\mathbb{E}[X] \neq 0.
\end{cases}
$$

O resultado final é o mesmo que o obtido por outros métodos @stern_conditional_1975.

# Aproximando durações de passeios aleatórios

Uma pergunta natural quando se discute aproximações é quanto a sua utilidade. Se
possível, é mais desejável utilizar resultados obtidos analiticamente, como, no
exemplo da "Ruína do Jogador" clássica, os apresentados na @sec-anali.

Nos cenários em que não é prático o desenvolvimento analítico, soluções
computacionais são buscadas. Estas soluções podem fornecer resultados teóricos
corretos, como na solução de sistemas lineares extensos que abordaremos na
[SESSÃO AQUI], ou aproximações pelo método de Monte Carlo, como descreve
@harrison_introduction_2010.

Ainda assim, a simulação também traz desvantagens para além da perda de precisão
e de interpretabilidade. Por exemplo, como abordado em @ritter_determining_2011,
um número considerável de simulações é necessário para garantir acurácia dos
dados e estabilidade. Diante disso, vê-se justificável a busca de estimadores
eficientes para a duração esperada de passeios aleatórios diversos.

## Um estimador heurístico

<!-- TODO: YUKIO: Criar seção com formulação do estimador -->
<!-- Baseando-se na mecânica clássica, @ishihara_um_2025 propôs um estimador para -->
<!-- passeios não unitários em meio homogêneo: -->

:::{#def-estimadorsimples}
Seja um jogo definido conforme a @def-modelodiscreto, com variável regra $X$ tal
que $\mathbb{E}(X) \neq 0$, valores $a$ e $N$. O estimador proposto para a
duração esperada desse jogo é dado por:

$$
\hat{\mathbb{E}}(\tau_{X, a, N}) = \begin{cases}
\frac{N-a}{\mathbb{E}(X)},  & \mathbb{E}(X) > 0, \\
\left \lvert \frac{a}{\mathbb{E}(X)} \right \rvert,  & \mathbb{E}(X) < 0.
\end{cases}
$$
:::

Primeiramente, o estimador da @def-estimadorsimples foi comparado com o
resultado da @eq-tempoteorico para jogos unitários. Retomando o 
@exm-modelodiscreto, temos, como $\mathbb{E}(X) = 0.2$:

$$
\begin{aligned}
\hat{\mathbb{E}}(\tau_{X, 50, 100}) = \frac{100}{0.2} = 250 \\
\mathbb{E}(\tau_{X, 50, 100}) = \frac{50}{0.6 - 0.4} - \frac{100}{0.6 - 0.4}
\left( \frac{1 - \left( \frac{0.4}{0.6} \right)^{50}}{1 - \left( \frac{0.4}{0.6}
\right)^{100}} \right) = 250
\end{aligned}
$$

Partimos para testá-lo em outros casos unitários. Dos nossos resultados,
obtemos, fixada a fortuna inicial $a=50$ e total $N$, e variando a probabilidade de
ganho $p$:

```{julia}
#| output: false
using Plots, LaTeXStrings

function estimador_simples(E_X, a, N)
    if E_X > 0
        return (N - a) / E_X
    elseif E_X < 0
        return - a / E_X
    else
        return NaN
    end
end

function tempo_teorico_unitario(a, N, p)
    q = 1 - p
    if p == q
        return a * (N - a)
    else
        return (a / (q - p)) - (N / (q - p)) * ((1 - (q / p)^a) / (1 - (q / p)^N))
    end
end

function comparar_estimador_unitario(a, N)
    ps = 0:0.01:1
    m = length(ps)
    estimados = Float64[]
    teoricos = Float64[]
    for p in ps
        E_X = (1 * p) + (-1 * (1 - p))
        push!(estimados, estimador_simples(E_X, a, N))
        push!(teoricos, tempo_teorico_unitario(a, N, p))
    end
    plt = plot(
        ps, estimados, label = "Duração estimada",
        xlabel = "Probabilidade de vitória (p)", ylabel = "Duração",
        legend = :topright,
    )
    plot!(ps, teoricos, label = "Duração esperada", linestyle = :dash)
    vline!(
        [0.48], label = L"p = 0.48 \Rightarrow \mathbb{E}(X) = -0.04",
        linestyle = :dashdot
    )
    vline!(
        [0.52], label = L"p = 0.52 \Rightarrow \mathbb{E}(X) = +0.04",
        linestyle = :dot
    )
    return plt
end
```

```{julia}
#| label: fig-comparacaoestimadorxteorico
#| fig-cap: "Comparação entre estimador simples e duração esperado em jogos unitários para $a = 50$ e $N = 100$ em função de $p$."
display(comparar_estimador_unitario(50, 100))
```

Notamos que o estimador apresenta bom comportamento nessa classe de jogos. Uma
inadequação de seu uso existe para casos em que $\mathbb{E}(X)$ se aproxima de
$0$, como indica o gráfico da @fig-comparacaoestimadorxteorico no intervalo
$[0.48, 0.52]$

Validado o estimador para grande parte dos casos mais simples, partimos para
análise em jogos não unitários. Para isso, utilizamos simulações de Monte Carlo
para obter valores aproximados de $\mathbb{E}(\tau_{X, a, N})$. Apresentamos no
@algo-montecarlosimples uma implementação simples desse processo
@harrison_introduction_2010, @ritter_determining_2011.

```pseudocode
#| label: algo-montecarlosimples
#| html-indent-size: "1.2em"
#| html-comment-delimiter: "//"
#| html-line-number: true
#| html-line-number-punc: ":"
#| html-no-end: false
#| pdf-placement: "htb!"
#| pdf-line-number: true

\begin{algorithm}
\caption{Monte Carlo Simples}
\begin{algorithmic}
\Procedure{MonteCarlo}{$MC, p, g, l, a, N$}
    \State $total\_tempo \gets 0$
    \For{$i =1$ to $MC$}
        \State $pos$ \gets $a$
        \While{$pos > 0$ and $pos < N$}
            \State $u \gets \Call{Sortear}{U(0,1)}$
            \If{$u < p$}
                \State $pos$ \gets $pos + g$
            \Else
                \State $pos$ \gets $pos - l$
            \EndIf
            \State $total\_tempo \gets total\_tempo + 1$
        \EndWhile
    \EndFor
    \State \Return $total\_tempo / MC$
\EndProcedure
\end{algorithmic}
\end{algorithm}
```

```{julia}
#| label: fig-comparacaoestimadorxsimulado
#| fig-cap: "Comparação entre estimador simples e duração simulada para $a = 50$, $N = 100$, valor de perda $1 e de ganho $2, em função de $p$. Simulados com $10.000$ iterações de Monte Carlo."
function monte_carlo_simples(MC, p, g, l, a, N)
    total_tempo = 0
    for i in 1:MC
        pos = a
        while pos > 0 && pos < N
            u = rand()
            if u < p
                pos += g
            else
                pos -= l
            end
            total_tempo += 1
        end
    end
    return total_tempo / MC
end

function comparar_estimador_montecarlo(MC, p, g, l, a, N)
    ps = 0:0.01:1
    m = length(ps)
    estimados = Float64[]
    simulados = Float64[]
    for p in ps
        E_X = (g * p) + (-l * (1 - p))
        push!(estimados, estimador_simples(E_X, a, N))
        push!(simulados, monte_carlo_simples(MC, p, g, l, a, N))
    end
    plt = plot(
        ps, estimados, label = "Duração estimada",
        xlabel = "Probabilidade de vitória (p)", ylabel = "Duração",
        legend = :topright, ylims = (0, 2500)
    )
    plot!(ps, simulados, label = "Duração simulada", linestyle = :dash)
    return plt
end

display(comparar_estimador_montecarlo(10_000, 0.5, 2, 1, 50, 100))
```

O estimador também apresenta bom desempenho para jogos não unitários, como
mostra a @fig-comparacaoestimadorxsimulado. Novamente, observa-se uma queda na
precisão do estimador à medida que $\mathbb{E}(X)$ se aproxima de $0$.

Com esses resultados, validamos o estimador proposto na @def-estimadorsimples
para passeios aleatórios em meio homogêneo, tanto unitários quanto não
unitários. Dessa forma, partimos para a análise de passeios mais complexos.

## Meio não-homogêneo

Ao tratarmos de passeios em meio não-homogêneo, precisamos descrever o
comportamento deste ambiente. No geral, podemos modelar um meio aleatório ou
determinístico. Em ambos casos, a variável regra $X$ dependerá da posição atual
do passeio, ou seja, $X = X_{S_n}$. Entretanto, enquanto no meio aleatório pode
ser modelado 


{{< pagebreak >}}

# Referências

:::{.refs}
::::
