--- 
title: "Aproximações para a duração média de passeios aleatórios"
bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl
lang: pt-BR

authors:
  - name: "Orientando: Gustavo Silva Garone"
  - name: "Orientadora: Elisabeti Kira"

abstract: > 
            Inspirados na física, propusemos aproximações para a duração de
            passeios aleatórios diversos, em especial, os de difícil derivação analítica.
            Para testar as aproximações, utilizamos simulações de Monte Carlo na linguagem
            Julia. Analisamos o desempenho desta linguagem comparando-a com a linguagem
            Python. Com modelos (passeios) mais sofisticados, utilizamos recursos
            computacionais para solução de sistemas lineares na construção de novas
            aproximações. Descrevemos o uso de paralelismo e de outras ferramentas. Exibimos
            e analisamos os resultados obtidos.

keywords:
    - Monte Carlo
    - Passeio Aleatório
    - Estimação
date: last-modified
date-format: long
format:
  pdf:
    documentclass: article
    fontsize: 12pt
    monofont: "Consolas"
    geometry:
      - top=20mm
      - left=20mm
      - bottom=20mm
      - right=20mm
    number-sections: true
    include-in-header:
      text: |
        \usepackage{authblk}
  html:
    theme: cosmo
  docx: default

engine: julia
execute:
  keep-ipynb: true
  # eval: false
fig-cap-location: top
---

# Introdução

Neste artigo, estudaremos a duração de passeios aleatórios e suas aproximações.
Temos como objetivo descrever modelos de passeios como a "Ruína do Jogador" de
Pascal, discutido em @edwards_pascals_1983, generalizando-o para múltiplas
dimensões. Abordaremos técnicas analíticas, computacionais e de estimativas para
a duração esperada destes passeios. 

Começamos por definir o modelo que será utilizado para descrever os passeios
aleatórios, acompanhado de exemplo. Então, apresentarmos o estimador descrito
por @ishihara_um_2025, e partimos para sua avaliação. Primeiramente, o
comparamos com resultados probabilísticos estabelecidos na área. Quando
avançamos para passeios em que resultados analíticos não são factíveis,
iniciamos a comparação do estimador com simulações de Monte Carlo.

Descrevemos e justificamos pela literatura a adoção da linguagem de programação
*Julia*, essencial para possibilitar a execução eficiente de simulações
computacionalmente intensivas em passeios mais complexos.

Em dimensões maiores, fornecemos, até onde é computacionalmente possível,
resultados exatos para a duração esperada de passeios aleatórios. Para obter
esses resultados, utilizamos métodos para solução de sistemas lineares extensos
simbólicos e empregamos técnicas de computação paralela, que serão brevemente
discutidas.

Este artigo priorizará a descrição do aspecto computacional dessa pesquisa.
Leitores são encorajados a consultar a referência @ishihara_um_2025 para uma
descrição mais detalhada da construção matemática do estimador e do modelo
utilizado.

# Modelando paseios aleatórios

## Modelo 

:::{#def-modelodiscreto, title="Modelo Discreto de Passeio Aleatório"}

Considere que o jogador $A$ começa com ma fortuna inicial com um total $\$N$ em
jogo,  $\$a$, $0 \leq a \leq N$,  fornecendo um espaço de estados $\{0, 1,
\dots, a, \dots, N\}$. Cada rodada produz um resultado aleatório independente
$X_i$, $i=1,2,\dots$, representando o ganho ou perda naquela etapa. Isso será
chamado de variável "regra". Após $n$ rodadas, a fortuna do jogador $A$ é dada
por

$$
    S_n = a + \sum_{i=1}^n X_i.
$$

A **duração do jogo** é o primeiro tempo $n$ tal que $S_n \leq 0$ (ruína) ou
$S_n \geq N$ (vitória) e é denotada por $\tau_{X, a, N}$.

Ao indexarmos $X_i$ na posição atual do passeio, $X_{i, S_n}$, podemos estender
esse modelo para passeios em meio aleatório.
:::


:::{#rem-uniforme} 
Em especial, se $X_{i, S_n} = X_i$ para todo possível valor $S_n$ (posição),
dizemos que o passeio está em meio uniforme (uniforme no espaço), pois a regra
não depende do estado atual do passeio. Analogamente, se
$X_{i, S_n} = X_{j, S_n}$ para todo $i \neq j$, dizemos que o passeio é
uniforme no tempo, pois a regra não depende do tempo $i$.
:::

Para ajudar no entendimento deste modelo, oferecemos um
exemplo:

:::{#exm-modelodiscreto}

:::{#exm-modelodiscretodim}

## Ruína do Jogador bidimensional

Considere um jogador apostando em um casino no lançamento de duas moedas
honestas. A primeira moeda define se apostará seus dólares ou seus euros. A
segunda moeda decide se ganhará ou perderá a jogada. No caso de derrota, deverá
deixar um dólar ou um euro com o casino, enquanto ganha essa quantidade no caso
de sucesso em sua aposta. Terminará o jogo quando atingir cem dólares ou cem
euros, ou caso vá à ruína (seu saldo chegue em zero em alguma das moedas). O
jogador começa com 50 dólares e 25 euros.

Podemos modelar esse jogo no modelo da @def-modelodiscreto, utilizando da
simplificação do @rem-uniforme. Tome $\pmb{V} = (v_1, v_2)$ com
$v_1 = v_2 = (0, 1, \dots, 100)$, $a = (50, 25)$ e

$$
X = \begin{cases}
(-1, 0), & 0.25 \\
(0, -1), & 0.25 \\
(1, 0), & 0.25 \\
(0, 1), & 0.25.
\end{cases}
$$

Note que é o mesmo para todo tempo $i$ e todo estado $v$ enquanto o jogo durar.

Após $5$ jogadas, o jogo tomou o seguinte percurso:
$$
\begin{aligned}
J(\pmb{V}, a, \pmb{x}) &= \{x_1, x_2, x_3, x_4, x_5\} \\
&= \{(1,0), (-1, 0), (0, 1), (0, 1), (-1, 0)\}.
\end{aligned}
$$

:::

Conforme a regra de parada $\tau$, o jogo encerrar-se-á assim que um elemento de
$S_n$ - isto é, uma moeda (dólar ou euro) - chegar em zero ou cem. No
@exm-modelodiscreto, é fácil ver que o jogo ainda não acabou, pois $S_5 = (49,
27)$.

Estamos interessados na duração esperada do jogo, ou seja, queremos encontrar
$E(\tau)$. Abordaremos técnicas analíticas, computacionais e estimativas para
este valor no restante deste artigo.


# Aproximando durações de passeios aleatórios

Uma pergunta natural quando se discute aproximações é quanto a sua utilidade. Se
possível, é mais desejável utilizar resultados obtidos analiticamente, como, no
exemplo da Ruína do Jogador clássica, os desenvolvidos em
@stern_conditional_1975. Conforme os passeios (e os modelos) complicam-se, pode
não ser possível, ou ser muito difícil, obter uma derivação analítica de
$E(\tau)$.

<!-- TOOD: ADICIONAR SESSÃO DO SISTEMA -->
Nos cenários em que não é prático o desenvolvimento analítico, soluções
computacionais são buscadas. Estas soluções podem fornecer resultados teóricos
corretos, como na solução de sistemas lineares extensos que abordaremos na
[SESSÃO AQUI], ou aproximações pelo método de Monte Carlo, como aborda
@harrison_introduction_2010.

Ainda assim, a simulação também traz desvantagens. Como descrito em
@ritter_determining_2011, um número considerável de simulações é necessário para
garantir acurácia dos dados e estabilidade. Além disso, com modelos mais
complexos, justamente os usados na resolução de problemas reais, estes problemas
se agravam. Diante disso, vê-se justificável a busca de estimadores eficientes
para a duração esperada de passeios aleatórios diversos.

## Ruína do Jogador e variações

Na Ruína do Jogador,






{{< pagebreak >}}

# Referências

:::{.refs}
::::
